### ISSUE TITLE
bwrap error after update

### ISSUE THREAD

**Issue by atuctuc** [flathub/de.mediathekview.MediathekView#14]
i run i MediathekView as user and updated de.mediathekview.MediathekView and now i get this err:

flatpak run de.mediathekview.MediathekView
bwrap: Can't mkdir /app/lib/ffmpeg: Read-only file system
error: ldconfig failed, exit status 256

**Comment by swsnr** [comment]
@atuctuc My bad.  See #15 for the fix.  Please test it (follow the instructions by the bot once the test build finished) and report whether it works.
