### ISSUE TITLE
Downloaded Files won't appear in the filesystem

### ISSUE THREAD

**Issue by albert180** [flathub/de.mediathekview.MediathekView#7]
Hey,
when I download Files with  the flatpak Mediathekview they dont appear in Nautilus nor in the terminal. In other Flatpak-Apps saving to the filesystem works.
I've also tried 
`sudo override --filesystem=home de.mediathekview.MediathekView`
but it doesn't change anything.

**Comment by lunaryorn** [comment]
Where do you save the files to?  The current version of this manifest only exports the standard "Downloads" directory; if you download files to that directory you'll see them in Nautilus.

Meanwhile you can find things in `~/.var/app/de.mediathekview.MediathekView/` which is the sandbox directory for the package.

> `sudo override --filesystem=home de.mediathekview.MediathekView`  

This is no valid flatpak command, so I don't really know what you did here.

But if I e.g. add the videos directory with `flatpak override --user --filesystem=xdg-videos de.mediathekview.MediathekView`, then I can download to the "Videos" directory and the file will appear in my ~/Videos directory.

**Comment by albert180** [comment]
Sorry I forgot the flatpak in the command written here, in the terminal I've added it obviously and no error returned, so I assumed it worked.
But using Flatseal to set /home it worked now. Thank you very much for pointing this out :-)
Maybe the manifest should be changed to expose /home, that way it's more beginner friendly:)

**Comment by lunaryorn** [comment]
> Maybe the manifest should be changed to expose /home, that way it's more beginner friendly:)

That's perhaps a good idea, since MediathekView can't use portals 🤔 

I'll see whether I can make a corresponding change.

**Comment by lunaryorn** [comment]
I've made a corresponding change in #8 and would appreciate if you would test it 🙂

**Comment by albert180** [comment]
Thank you!
 I will test it this evening :)

**Comment by albert180** [comment]
It work's fine :)
